# Cluster configuration

default-resources:
    slurm_account:   cli99
    slurm_partition: main
    runtime: "'120'" # must be 120 if we want to run in debug qos
    nodes: 2
    tasks: 20
    cpus_per_task: 2
    mem_mb_per_cpu: 2G
    slurm_extra: "'--mail-user=baeza@recerca.clinic.cat --qos=debug'"
immediate-submit: False
jobs: 100
keep-going: true
latency-wait: 120
max-jobs-per-second: 100
max-status-checks-per-second: 15
notemp: true
printshellcmds: true
scheduler: greedy
conda-frontend: "conda"
#use-conda: true
verbose: true