# Cluster configuration

cluster:
    mkdir -p slgpfs/projects/rcli/rcli186814/log/{rule}/ &&
    sbatch
        --job-name={rule}-{wildcards}
        --account=cli99
        --partition=debug
        --mail-user=baeza@recerca.clinic.cat
        --mail-type=FAIL
        --nodes=1
        --ntasks=9
        --cpus-per-task={threads}
        --mem-per-cpu=1024MB
        --time="2:00:00"
        --output=slgpfs/projects/rcli/rcli186814/log/{rule}/{rule}.{wildcards}.out
        --error=slgpfs/projects/rcli/rcli186814/log/{rule}/{rule}.{wildcards}.err
threads: 6
conda-frontend: "conda"
immediate-submit: False
jobs: 100
keep-going: true
latency-wait: 120
max-jobs-per-second: 100
max-status-checks-per-second: 10
notemp: true
printshellcmds: true
scheduler: greedy
use-conda: true
verbose: true