# Cluster configuration

default-resources:
    slurm_account:   cli99
    slurm_partition: cli
    runtime: "2:00:00"
    nodes: 1
    tasks: 9
    cpus_per_task: 6
    mem_mb_per_cpu: 1024MB
    slurm_extra: "'--mail-user=baeza@recerca.clinic.cat --mail-type=ALL --output=slgpfs/projects/rcli/rcli186814/rnaseq_virginia/logs/{rule}/{rule}.{wildcards}.out --error=slgpfs/projects/rcli/rcli186814/rnaseq_virginia/logs/{rule}/{rule}.{wildcards}.err'"
immediate-submit: False
jobs: 100
keep-going: true
latency-wait: 120
max-jobs-per-second: 100
max-status-checks-per-second: 10
notemp: true
printshellcmds: true
scheduler: greedy
conda-frontend: "conda"
use-conda: true
verbose: true