# Cluster configuration

cluster:
    mkdir -p slgpfs/projects/rcli/rcli186814/log/{rule}/ &&
    sbatch
        --job-name={rule}-{wildcards}
        --account={resources.account}
        --partition={resources.partition}
        --mail-user={resources.email}
        --mail-type={resources.mail_on}
        --nodes=1
        --ntasks=9
        --cpus-per-task={threads}
        --mem-per-cpu={resources.mem_mb}MB
        --time={resources.time}
        --output=slgpfs/projects/rcli/rcli186814/log/{rule}/{rule}.{wildcards}.out
        --error=slgpfs/projects/rcli/rcli186814/log/{rule}/{rule}.{wildcards}.err
resources:
  - account=cli99
  - partition=main
  - email=baeza@recerca.clinic.cat
  - mail_on=FAIL
  - mem_mb=1024
  - time="2:00:00"
threads: 6
conda-frontend: "conda"
immediate-submit: False
jobs: 4999
keep-going: true
latency-wait: 120
max-jobs-per-second: 100
max-status-checks-per-second: 10
notemp: true
printshellcmds: true
scheduler: greedy
use-conda: true
verbose: true