threads: 24

# Define the directory containing the FASTQ files
fastq_dir_paired_unmerged: "FASTQ/rna_paired/unmerged"

# Define the directory containing the FASTQ files
fastq_dir_single_end: "FASTQ/single_end"