samples:
    FASTQ/Zwt1_02158AAC_ATCACG.fastq:
    FASTQ/Zwt2_02160AAC_TTAGGC.fastq:
    FASTQ/Zwt3_02162AAC_GATCAG.fastq:
    FASTQ/Zcr1_02159AAC_CGATGT.fastq:
    FASTQ/Zcr2_02161AAC_CAGATC.fastq:
    FASTQ/Zcr3_02163AAC_AGTTCC.fastq:

# CONFIG FILE NOT USED AT THIS TIME 2/08/2024